### ISSUE TITLE
Issue running "npm run protractor" on Ubuntu 12.04

### ISSUE THREAD

**Issue by declan** [angular/angular-seed#200]
I cloned the repository and followed instructions in the README. Unit tests run with no problem, and the application works in-browser. However, the protractor tests fail with this error message:

    ------------------------------------
    PID: 20518 (capability: chrome #1)
    ------------------------------------

    Starting selenium standalone server...

    events.js:72
             throw er; // Unhandled 'error' event
              ^
    Error: spawn ENOENT
        at errnoException (child_process.js:998:11)
        at Process.ChildProcess._handle.onexit (child_process.js:789:34)
     [launcher] Runner Process Exited With Error Code: 8

The error is the same as reported in #189. I tried updating JDK, which fixed the issue in that post, but it didn't do anything for me (is JDK even involved on Linux?).

Also, I've already tried running protractor directly

    node_modules/.bin/protractor test/protractor-conf.js

and get the same error.

**Comment by gkalpak** [comment]
I assume this has been solved (if not please open a new issue).

You will indeed need JDK installed, since it is needed for the Selenium Standalone Server used by Protractor (see [here][1] for more info).
<sub>I think you could also work around this, by setting `directConnect: true` and `chromeOnly: true` in your `protractor.conf.js`, but then you won't be able to run tests on other browsers.</sub>

[1]: https://docs.angularjs.org/tutorial#common-issues
