### ISSUE TITLE
What happened to the sane, classic angular layout?

### ISSUE THREAD

**Issue by rdodev** [angular/angular-seed#250]
last version of Yeoman generator, it produces something along the lines of:
```
scripts/
 controllers/
 tests/
index.html
app.js
bower_components
views/
```

This seed makes a very opinionated and confusing decision to have an app with sub-apps and each sub-app with a useless example and bunches router, controllers, etc in the same file because reasons, apparently. 

*If* the point of this seed if to bootstrap people fast, you _need_ to flatten it, reduce indirection and make it easy for people to understand how the basic building blocks of angular work.

My 2c

**Comment by Tmarty** [comment]
+1

**Comment by JoshSpears3** [comment]
@rdodev @Tmarty When a project reaches a certain size, understanding the code can become very time consuming. Especially when a bug rises from the dark depths of hell. The reason for breaking this angular-seed into views is based on modularity. If something breaks, you should easily be able to find it based on the application, because each directory belongs to itself, and interferes with no other code. It's also easier to read. (Especially if your joining a project that's based around Angular) 

```
app/
 - view1/
     - view1.js
     - view1.html
 - view2/
     - view1.js
     - view1.html
``` 
Compared to:

```
app/
 - controllers/
     - src/
          - view1Controller.js
          - view2Controller.js
     - controllers.js
 - directives/
     - src/
          - view1Directive.js
          - view2Directive.js
     - directives.js
 - filters/
     - src/
          - view1Filters.js
          - view2Filters.js
     - filters.js
 - services/
     - src/
          - view1Services.js
          - view2Services.js
     - services.js
```

**Comment by Tmarty** [comment]
@JoshSpears3 That makes a lot of sense actually. I will try this out in a project and see for myself. Thanks for explaining the reasoning behind this layout.
