### ISSUE TITLE
Error with npm start and npm install 

### ISSUE THREAD

**Issue by rahuldoc** [angular/angular-seed#313]
I am a beginner and I am getting errors after cloning this project.
I am getting these errors on running npm install.
npm http GET https://registry.npmjs.org/bower
npm http GET https://registry.npmjs.org/http-server
npm http GET https://registry.npmjs.org/jasmine-core
npm http GET https://registry.npmjs.org/karma
npm http GET https://registry.npmjs.org/karma-chrome-launcher
npm http GET https://registry.npmjs.org/karma-firefox-launcher
npm http GET https://registry.npmjs.org/karma-jasmine
npm http GET https://registry.npmjs.org/karma-junit-reporter
npm http GET https://registry.npmjs.org/protractor
npm http GET https://registry.npmjs.org/shelljs

npm ERR! Error: failed to fetch from registry: karma
npm ERR!     at /usr/share/npm/lib/utils/npm-registry-client/get.js:139:12
npm ERR!     at cb (/usr/share/npm/lib/utils/npm-registry-client/request.js:31:9)
npm ERR!     at Request._callback (/usr/share/npm/lib/utils/npm-registry-client/request.js:136:18)
npm ERR!     at Request.callback (/usr/lib/nodejs/request/main.js:119:22)
npm ERR!     at Request.<anonymous> (/usr/lib/nodejs/request/main.js:212:58)
npm ERR!     at Request.emit (events.js:88:20)
npm ERR!     at ClientRequest.<anonymous> (/usr/lib/nodejs/request/main.js:412:12)
npm ERR!     at ClientRequest.emit (events.js:67:17)
npm ERR!     at HTTPParser.onIncoming (http.js:1261:11)
npm ERR!     at HTTPParser.onHeadersComplete (http.js:102:31)
npm ERR! You may report this log at:
npm ERR!     http://bugs.debian.org/npm
npm ERR! or use
npm ERR!     reportbug --attach /home/rahul/angular-seed/npm-debug.log npm
npm ERR! 
npm ERR! System Linux 3.5.0-54-generic
npm ERR! command "node" "/usr/bin/npm" "install"
npm ERR! cwd /home/rahul/angular-seed
npm ERR! node -v v0.6.12
npm ERR! npm -v 1.1.4
npm ERR! message failed to fetch from registry: karma
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/rahul/angular-seed/npm-debug.log
npm not ok
.

Please guide me a way to resolve these errrors. Any help would be appreciated.

**Comment by garora** [comment]
@rahuldoc - are you following steps, mentioned here [ReadMe](https://github.com/angular/angular-seed/blob/master/README.md) ?
Looks you missed something, I tried with a fresh clone and there're no such errors.

I suggest go through the above ReadMe file once again and try and trust it will definitely work :+1:

**Comment by rahuldoc** [comment]
Hi Gaurav,

I thank you for replying but as you suggested I went through ReadMe file again and started a new project. I tried uninstalling nodejs and npm and installing them again but I am still getting same errors again. 
Please let me know where I am going wrong or missing something. After running npm install it is giving me same errors as before.


rahul@rahul-Inspiron-7520:~/Desktop/angular-seed$ npm install
npm http GET https://registry.npmjs.org/bower
npm http GET https://registry.npmjs.org/http-server
npm http GET https://registry.npmjs.org/jasmine-core
npm http GET https://registry.npmjs.org/karma
npm http GET https://registry.npmjs.org/karma-chrome-launcher
npm http GET https://registry.npmjs.org/karma-firefox-launcher
npm http GET https://registry.npmjs.org/karma-jasmine
npm http GET https://registry.npmjs.org/karma-junit-reporter
npm http GET https://registry.npmjs.org/protractor
npm http GET https://registry.npmjs.org/shelljs

npm ERR! Error: failed to fetch from registry: jasmine-core
npm ERR!     at /usr/share/npm/lib/utils/npm-registry-client/get.js:139:12
npm ERR!     at cb (/usr/share/npm/lib/utils/npm-registry-client/request.js:31:9)
npm ERR!     at Request._callback (/usr/share/npm/lib/utils/npm-registry-client/request.js:136:18)
npm ERR!     at Request.callback (/usr/lib/nodejs/request/main.js:119:22)
npm ERR!     at Request.<anonymous> (/usr/lib/nodejs/request/main.js:212:58)
npm ERR!     at Request.emit (events.js:88:20)
npm ERR!     at ClientRequest.<anonymous> (/usr/lib/nodejs/request/main.js:412:12)
npm ERR!     at ClientRequest.emit (events.js:67:17)
npm ERR!     at HTTPParser.onIncoming (http.js:1261:11)
npm ERR!     at HTTPParser.onHeadersComplete (http.js:102:31)
npm ERR! You may report this log at:
npm ERR!     <http://bugs.debian.org/npm>
npm ERR! or use
npm ERR!     reportbug --attach /home/rahul/Desktop/angular-seed/npm-debug.log npm
npm ERR! 
npm ERR! System Linux 3.5.0-54-generic
npm ERR! command "node" "/usr/bin/npm" "install"
npm ERR! cwd /home/rahul/Desktop/angular-seed
npm ERR! node -v v0.6.12
npm ERR! npm -v 1.1.4
npm ERR! message failed to fetch from registry: jasmine-core
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/rahul/Desktop/angular-seed/npm-debug.log
npm not ok


Please guide me through this. I also tried to switch to windows 8 but to no avail. Any help would be heartly appreciated. For my project I just need to see the default app running on localhost server.
But I am still stuck at that.

**Comment by Quaggie** [comment]
http://stackoverflow.com/questions/12913141/message-failed-to-fetch-from-registry-while-trying-to-install-any-module
Try this.

**Comment by botheredbybees** [comment]
I had the following 2 errors with my install:

/usr/bin/env: ‘node’: No such file or directory
 
solved by making a symlink to nodejs:

`sudo ln -s /usr/bin/nodejs /usr/bin/node`



and then I got this error:

npm ERR! Linux 4.4.0-47-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! angular-seed@0.0.0 postinstall: `bower install`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the angular-seed@0.0.0 postinstall script 'bower install'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the angular-seed package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     bower install
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs angular-seed
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls angular-seed
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /var/www/html/angular-novice2ninja/npm-debug.log

turns out I needed to install bower after installing npm and node:

`sudo npm install -g bower`

**Comment by gkalpak** [comment]
Closing since the original issue is too old (and hopefully irrelevant by now). If anyone is still facing problems with `angular-phonecat` itself, please open a new issue.
