### ISSUE TITLE
Unable to post an angular-seed based project on github

### ISSUE THREAD

**Issue by rus-techie** [angular/angular-seed#326]
I have made a project based on angular-seed. Now when I am trying to push it in my repository on github, it gives me an error: Permission to angular/angular-seed.git denied. The requested URL returned error: 403
Please suggest.

**Comment by skylarjhdownes** [comment]
Your problem is most likely related to git and/or github, not the angular-seed project.  You might find this SO article helpful: http://stackoverflow.com/questions/7438313/pushing-to-git-returning-error-code-403-fatal-http-request-failed

**Comment by gkalpak** [comment]
It seems you are trying to upload your project as `https://github.com/angular/angular-seed.git` (which is obviously not possible and not what you intend).

I don't know how exactly you are trying to push it to github, but you should configure git first.
Setting the `origin` to your own repo might be enough: `git remote add origin https://github.com/<username>/<reponame>`

Closing since this is not related to `angular-seed`.
