### ISSUE TITLE
Typescript + Module Loader + Routing

### ISSUE THREAD

**Issue by AmirSasson** [angular/angular-seed#344]
due to some reasons, we cannot upgrade our environment to ng2. yet.
Currently we seek for a fine example of an app that uses : 
1. Typescript code 
2.Some Module loader (such as SystemJS)
3. Using Routes

there are some repos that own Typescript and  SystemJS but none uses Routing.
i Have already a starter repo that i Can share, but still didnt figure out how to combine the routing.

**Comment by gkalpak** [comment]
This is a basic seed app for Angular 1 projects. There are several other seed projects and it is not possible to cover all possible combinations of tools and languages in one seed (e.g. ES5, ES6, TypeScript, SystemJS, Webpack etc).

I'm going to close this, since incorporating TypeScript is outside of the scope of this project.

--
That said, I can't think why TypeScript/SystemJS would stand in the way of routing. You ask for help on one of the [general support channels][1].

[1]: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question
