### ISSUE TITLE
Update deprecated packages

### ISSUE THREAD

**Issue by LJNielsenDk** [angular/angular-seed#382]
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated node-uuid@1.4.7: use uuid module instead

**Comment by gkalpak** [comment]
I couldn't find `node-uuid` as a sub-dependency. Regarding `minimatch@0.3.0`, it is a transient dependency through `protractor@4.0.11` -> `jasmine@2.4.1`. We are using the latest version of protractor, so we can't do anything. It is protractor that needs to be updated to use a newer version of jasmine (but I don't know what implications this may have for them).

Closing, since there is nothing actionable for `angular-seed`.
