### ISSUE TITLE
Adding HMR

### ISSUE THREAD

**Issue by torabian** [angular/angular-seed#393]
I think it's more interesting to add hmr support for this seed.

**Comment by gkalpak** [comment]
We are trying to keep this seed unopinionated and basic (i.e. only concerned with the AngularJS stuff), so that it can be easily adapted to any workflow. If I am not mistaken, HMR (if at all possible) would require the introduction of a build tool/bundler and impose more restrictions.

This is outside the scope of this seed.
<sub>Note, this is the AngularJS (1.x) seed.</sub>
