### ISSUE TITLE
npm install ERROR

### ISSUE THREAD

**Issue by dice1996** [angular/angular-seed#400]
[npm-debug.txt](https://github.com/angular/angular-seed/files/832147/npm-debug.txt)
I'm sending you debug file for npm install! Take a look and let me know what's wrong.

**Comment by gkalpak** [comment]
What does your `package.json` look like?

**Comment by parloti** [comment]
I was having the same problem.

npm ERR! node v7.7.3
npm ERR! npm  v4.1.2
npm ERR! code ELIFECYCLE
npm ERR! angular-seed@0.0.0 postinstall: `bower install`
npm ERR! Exit status 1

I tried...

git config --global url."https://".insteadOf git://
npm install -g bower
bower install

...unsuccessfully.

Then I got it:
**ENOGIT git is not installed or not in the PATH**

So I left the cmd aside and executed in:
"C:\Program Files\Git\git-bash.exe"

Worked perfectly.

**Comment by pmcavoy89** [comment]
@dice1996 I think you need to change the permissions on the `node_modules` directory to have the executable permission for your user. This will allow the `bower install` command to be run from the `node_modules` directory.

The reason @parloti works is because the user has access to run the `bower` from the global space of `npm`. This is okay to do but if you have multiple projects that use `bower` and they have different versions, it may become painful to manage from the global space instead of the project space.

**Comment by gkalpak** [comment]
This is unlikely since usually the user already has rights to execute files in the `node_modules/` (assuming it is the same user tht cloned the git repository in the first place).

In any case, there is not enough info to investigate and we haven't heard back from the OP, so closing.
Thx @parloti and @pmcavoy89 for chiming in.

**Comment by pmcavoy89** [comment]
This is what actually happened to me @gkalpak when I forked it. Had to change the permissions to get it to work. Not sure why it happened though.

**Comment by gkalpak** [comment]
¯\\\_(ツ)\_/¯
