### ISSUE TITLE
Any view shows index page

### ISSUE THREAD

**Issue by devthedeveloper** [angular/angular-seed#411]
When I hit directly http://localhost:8000/view1 it goes to http://localhost:8000/view1/ and shows the index page like this

![image](https://cloud.githubusercontent.com/assets/9020021/24840039/72c72328-1d83-11e7-81e1-bff9c4f37f50.png)

its same with any route.

**Comment by gkalpak** [comment]
This is expected. Since by default the app is in hashbang mode, the URL for `view1` would be http://localhost:8000/#!/view1. If you want to use HTML5 mode (where yu can get cleaner URLs) you need a server that can be configured to rewrite appropriate URLs to `index.html`. 

For more info, take a look [here][1].

[1]: https://docs.angularjs.org/guide/$location
